name: opyrability-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9.0
  - setuptools>=61.2.0
  - numpy>=1.24.1
  - scipy>=1.10.0
  - tqdm>=4.64.0
  - matplotlib>=3.6.2
  - jax>=0.4.0
  - cvxopt>=1.2.7
  - cyipopt>=1.2.0
  - opyrability >= 1.1
  - polytope >=0.2.4