[build-system]
requires = ["setuptools>=61.2.0", "poetry-core", "wheel", "setuptools_scm[toml]>=7.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]

[tool.poetry]
name = "codes-pypo"
version = "0.0.1"
description = "Python-based process operability package"
authors = ["Victor Alves"]
license = "GPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering/Process Systems Engineering",
]
packages = [{ include = "pypo.py", from = "src" },
			{include =   "PolyhedraVolAprox.py", from="src"}]
exclude = ["*.tests", "*.tests.*", "tests.*", "tests", "*.obsolete", "*.obsolete.*", "obsolete.*", "obsolete", ]

[tool.poetry.dependencies]
python = "^3.9.0"
numpy = "^1.24.1"
scipy = "^1.10.0"
tqdm = "^4.64.1"
matplotlib = "^3.6.2"
#cyipopt = { git = "https://github.com/mechmotum/cyipopt.git", branch = "master"}
polytope = {git = "https://github.com/tulip-control/polytope.git", branch = "main"}

[tool.poetry.extras]
#jaxlib   =   {url = "https://whls.blob.core.windows.net/unstable/cpu/jaxlib-0.3.25-cp39-cp39-win_amd64.whl"}
#jax[cpu]="0.3.25"