[tool.poetry]
name = "pyprop"
version = "0.0.1"
description = "Process Operability Calculations in Python"
authors = ["Victor Alves"]
license = "GPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering/Process Systems Engineering",
]
packages = [{ include = "pyprop.py", from = "src" },
			{include =   "PolyhedraVolAprox.py", from="src"}]
exclude = ["*.tests", "*.tests.*", "tests.*", "tests", "*.obsolete", "*.obsolete.*", "obsolete.*", "obsolete", ]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.1"
scipy = "^1.10.0"
polytope = "^0.2.3"
tqdm = "^4.64.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
