{% set name = "opyrability" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CODES-group/opyrability/archive/{{ version }}.tar.gz
  sha256: ecf25c8791d65af554995bff4cc1cf3eb8f28317cdc0e1d3d5ce7b204d3f71a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=61.2.0
    - poetry-core
    - wheel
    - setuptools-scm >=7.1.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pip
    - pip:
        - polytope >=0.2.4,<0.3.0
    - numpy >=1.24.1,<2.0.0
    - scipy >=1.10.0,<2.0.0
    - tqdm >=4.64.1,<5.0.0
    - matplotlib-base >=3.6.2,<4.0.0
    - jax >=0.4.13,<0.5.0
    - cvxopt >=1.2.7,<2.0.0

test:
  imports:
    - PolyhedraVolAprox
    - opyrability
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - codes-group
