{% set name = "opyrability" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CODES-group/opyrability/archive/{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=61.2.0
    - poetry-core
    - wheel
    - setuptools-scm >=7.1.0
    - pip
    - cython
  run:
    - python >=3.9.0,<4.0.0
    - cython
    - polytope >=0.2.4,<0.3.0
    - numpy 
    - scipy
    - tqdm
    - matplotlib-base
    - jaxlib >=0.4.13,<0.5.0
    - jax >=0.4.13,<0.5.0
    - cvxopt
    - cyipopt >=1.2.0, <2.0.0

test:
  imports:
    - opyrability


about:
  home: https://github.com/CODES-group/opyrability
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - codes-group
