{% set name = "opyrability" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CODES-group/opyrability/archive/{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=61.2.0
    - poetry-core
    - wheel
    - setuptools-scm >=7.1.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - polytope >=0.2.4,<0.3.0
    - numpy >=1.24.1,<2.0.0
    - scipy >=1.10.0,<2.0.0
    - tqdm >=4.64.1,<5.0.0
    - matplotlib-base >=3.6.2,<4.0.0
    - jaxlib >=0.4.13,<0.5.0
    - jax >=0.4.13,<0.5.0
    - cvxopt >=1.2.7,<2.0.0
    - cyipopt >=1.2.0, <2.0.0

test:
  imports:
    - PolyhedraVolAprox
    - opyrability
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - codes-group
