{% set version = "1.4.3" %}

package:
  name: opyrability
  version: {{ version }}

source:
  git_url: https://github.com/CODES-group/opyrability.git
  git_rev: {{ version }}

build:
  script: {{ PYTHON}} -m pip install . -vv

requirements:
  host:
    - python {{ python }}
    - setuptools >=61.2.0
    - poetry-core
    - wheel
    - setuptools-scm >=7.1.0
    - pip
    - cython
  run:
    - python {{ python }}
    - cython
    - numpy 
    - scipy
    - cvxopt
    - tqdm
    - matplotlib
    - polytope >=0.2.4,<0.3.0
    - jaxlib >=0.4.13,<0.5.0
    - jax >=0.4.13,<0.5.0
    - cyipopt >=1.2.0, <2.0.0

test:
  imports:
    - opyrability


about:
  home: https://github.com/CODES-group/opyrability
  license: MIT

