{% set version = "1.3.3" %}
{% set data = load_setup_py_data() %}
package:
  name: opyrability
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=61.2.0
    - poetry-core
    - wheel
    - setuptools-scm >=7.1.0
    - pip
    - cython
  run:
    - python >=3.9.0,<4.0.0
    - cython
    - polytope >=0.2.4,<0.3.0
    - numpy 
    - scipy
    - tqdm
    - matplotlib-base
    - jaxlib >=0.4.13,<0.5.0
    - jax >=0.4.13,<0.5.0
    - cvxopt
    - cyipopt >=1.2.0, <2.0.0

test:
  imports:
    - opyrability


about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}

