{% set version = "1.3.7" %}

package:
  name: opyrability
  version: {{ version }}

source:
  git_url: https://github.com/CODES-group/opyrability.git
  git_rev: {{ version }}

build:
  script: {{ PYTHON}} -m pip install . -vv

requirements:
  build:
    - python>=3.9
  host:
    - python>=3.9
    - setuptools
    - poetry-core
    - wheel
    - setuptools-scm
    - pip
    - cython
  run:
    - python>=3.9
    - cython
    - polytope >=0.2.4,<0.3.0
    - numpy 
    - scipy
    - tqdm
    - matplotlib-base
    - jaxlib >=0.4.13,<0.5.0
    - jax >=0.4.13,<0.5.0
    - cvxopt
    - cyipopt >=1.2.0, <2.0.0

test:
  imports:
    - opyrability


about:
  home: https://github.com/CODES-group/opyrability
  license: MIT

