name: publish to conda

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: siboles/conda-publish-action@v1
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_SECRET }}
        platforms: 'win osx linux'
